#cloud-config

runcmd:
    - [ sudo, systemctl, enable, teleport.service ]
    - [ sudo, systemctl, start, teleport.service ]

device_aliases:
    persistent: /dev/sdb
disk_setup:
    persistent:
        table_type: gpt
        layout: [100]

fs_setup:
    - label: fs1
      filesystem: ext4
      device: persistent.1

mounts:
    - ["persistent.1", "/persistent"]

apt:
    sources:
        teleport:
            keyserver: "https://deb.releases.teleport.dev/teleport-pubkey.asc"
            keyid: "0c5e 8ba5 658e 320d 1b03 1179 c87e d53a 6282 c411"
            source: "deb [signed-by=$KEY_FILE] https://deb.releases.teleport.dev/ stable main"

package_update: true
package_upgrade: true
packages:
    - teleport

hostname: teleportProxy

write_files:
    - path: /etc/teleport.yaml
      content: |
        version: v2
        teleport:
          nodename: 10.58.0.102
          data_dir: /persistent/teleport
          auth_token: "26184819c61eb197e8e53b59c9defa5b"
          ca_pin: "sha256:fe8dc76c785206ce4fdb04c27362abeeb836c50df3e7e8e25fbe3d74f7b9b27b"
          auth_servers:
              - 10.58.0.101:3025
          log:
            output: stderr
            severity: INFO
            format:
              output: text
          diag_addr: ""
        auth_service:
          enabled: "no"
        ssh_service:
          enabled: "yes"
          labels:
            level: "normal"
          commands:
          - name: hostname
            command: [hostname]
            period: 1m0s
        proxy_service:
          enabled: "no"

users:
    - name: thotgamma
      passwd: "$1$qRuAGKAb$zjFxdG6kTPwSrnnfT16ar1"
      lock_passwd: false
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDrc9PGJ+ViqzVOh5xuOHiZDAmu4X12VVo/YjT3+XCfwS27K7UBs67BdI6P3OYhxDotUQ01tYJQOlZMOCVDfglqqUlhF4RPfAA5L412Kd545AGqOWC/1rQbazr9wlGQC6rjrCRePIxCtxKk2NE5su+jT842W7D6WnKn9vEQ7lfHAGD30APjvI8VdxSY3DwqApeeXwlIu7iq0pZ9c01mcJjj3eVePLprYRai3zZ4vVKeXoIzqtP1ISJFO9r+oLT7r72iK3GxZR81KOnhQF+b+Ur1NW1a5YQwHlb7ZcNFwQ8yPfTYsykABhFNl42Yhg8huuSdVTc5PLBnlmw4eZY1lCsRbNQ83lY+ilPOi8VgdkoMNDD/rEpnz0H4IX1381DpqTZRBAilaObdhXv3edK2womRtRRd3OKcKuyP3arDfYIZco48nWLcW7QUMI+P56GwD4L2IdvuAKawXz+WuraQ0+Y3MLWDouiKI0+lUASSNinDo5Sk028gwo8Ep4pL82870qc= thotgamma@WHITETT


